dist: focal
language: python
python:
  - "3.9.1"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install pandoc default-jre
  - pip install poetry
install:
  - poetry install
  - poetry shell
# command to run tests
script:
  - pytest