language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
  - poetry shell
# command to run tests
script:
  - pytest